### ISSUE TITLE
Stopped working entirely

### ISSUE THREAD

**Issue by IZA09** [DominikDoom/a1111-sd-webui-tagcomplete#231]
after reinstalling automatic1111 after a decently long break, i reinstalled the extension through the interface itself. unfortunately nothing seems to be active, nothing pops up as i type, and ive tried removing all other extensions, installing the extension through the other methods, and even just copied over the extension from my old 1111 folder because i knew it worked there, unfortunately nothing semes to be working. the settings pop up and by all accounts the interface recognizes the extension, but literally nothing is happening. something tells me it has to do with the updated interface but im not entirely sure.

edit: i reverted back down to 1.5.2 from the latest version i was initially using 1.6.0 and it works like it should. so evidently something in the newest version is messing with the extension.

**Comment by DominikDoom** [comment]
I am using it fine on 1.6.0, so that shouldn't be the issue. Fresh install through the UI also works without problems for me.

Some things to try out:
- Make sure there is no old installation in a different folder still around. Duplicates will interfere with each other.
- Open the browser console (CTRL+SHIFT+I) and tell me if you see any error that originates from or mentions tagAutocomplete.js, or send me the log / a screenshot
- If there are no errors visible there, try disabling all other extensions temporarily to make sure it's not some other incompatibility
- Back up & delete or rename your `<webui root>/config.json` file. This will reset all settings to the default, to ensure that the issue isn't some kind of misconfiguration

The most important one is checking for errors in the browser console, I need that info to help you further.

**Comment by IZA09** [comment]
<img width="1244" alt="Screenshot 2023-09-09 071311" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/03e9e1f1-9860-4290-8de7-07fad59998dd">

unfortunately i don't see a thing. I've gone through your steps and still nothing. the extension is the only one active as well. nowhere on the web console or my cmd console do i see an error. ive tried on a different browser just in case but no luck. its a bit frustrating at this point.

**Comment by DominikDoom** [comment]
Can you show me your settings page for tag autocomplete? There shouldn't be breaking changes regarding the webui version there, but that's the only thing I can think of for now where something could be wrong, if no errors show anywhere else.

**Comment by IZA09** [comment]
![127 0 0 1_7860____theme=dark](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/4562cf62-491e-4318-9dfc-606efcaf6273)

everything is default and untouched

**Comment by DominikDoom** [comment]
If you just enter `allTags` in your browser console, does anything show up? To make sure the file gets loaded.

**Comment by IZA09** [comment]
<img width="587" alt="Screenshot 2023-09-09 073728" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/ec134833-3730-4f00-89d6-7b5e35a39265">

this pops up. i apologize im not very tech savvy its possible i could be missing some kind of super specific prerequisite. but then again, it worked just earlier with the older ui.

**Comment by DominikDoom** [comment]
Well, if that isn't found on the webui page, it means the javascript part of the extension isn't loaded at all.
Why that is the case is a different question.

You can try closing & restarting the webui entirely and then force-refresh the page with CTRL+F5 after it is loaded up again. Might be a cache issue which would be cleared in that case.
Also, do a file search for "__globals.js" in your extensions folder. It might be a problem if some other extension uses the same name.

**Comment by IZA09** [comment]
<img width="677" alt="Screenshot 2023-09-09 075113" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/49626410-3397-439c-a073-8ecb1a7d078b">

i should probably mention that im using opera.
running alltags in chrome brings different results, though neither are affected by CTRL+F5.

and lastly as this is the only extension in the extension folder, there is only one "__globals.js". its own.

i have a sneaking suspicion this is some form of user error and a apologies for bothering with this if the solution ends up being something trivial.

**Comment by DominikDoom** [comment]
But the completion itself doesn't work in chrome too, right? Both are chromium, so they should be similar enough.
With all these other things we already tried I am running out of ideas too. I never had a case this far where it doesn't work without any error messages being shown and with default options. And also no clue why this only affects v1.6.0 for you, pretty sure nothing about extension loading changed there.

Another thing to try would be right clicking the prompt textbox and choosing Inspect.
If the extension is loaded correctly it would show `autocompleteParent` next to it:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/d2c4575a-26a2-4ea1-953b-371295a1705c)
 
The only other thing I can think of would be to make sure no browser extension like an adblocker interferes, and if all else fails trying a fresh install of the webui itself / deleting and regenerating the venv. But that seems unlikely.

**Comment by IZA09** [comment]
<img width="224" alt="Screenshot 2023-09-09 081618" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/7b3307ce-525b-48e1-a5e2-4d11ec7abdf6">

its there.

yes in chrome nothing pops up all the same. i recently switched to opera so i assumed it was some weird incompatibility but apperantly its not. i dont mind just rolling back to the older ui, but id still like to understand what it is that's wrong here.

**Comment by DominikDoom** [comment]
Huh, it *is* there? Now I really wonder what's going on here.
As a test, keep open this view and have an eye on it while you type something. It should change the `display: none;` at the bottom to `display: flex;`.
If it doesn't, try selecting it in the list and uncheck this:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/279c48cb-38c9-4240-a3e3-f2a395e12b77)
(should be either to the right or below the list of elements)

**Comment by IZA09** [comment]
<img width="88" alt="Screenshot 2023-09-09 084554" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/7b28e961-9631-45b7-804b-f95ed2cd336e">

well here's a deviation. mine looks nothing like that. 

<img width="937" alt="Screenshot 2023-09-09 084944" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/5206ae63-a220-41fa-9ee5-ef9a11ec3ada">

this is... correct?

**Comment by DominikDoom** [comment]
No no, I meant select the autocompleteParent one below that

**Comment by IZA09** [comment]
oh whoops. well yes it does in fact change from "none" to "flex" along with a change in the px, so it looks like its working, but something is preventing the actual asset from showing up

**Comment by DominikDoom** [comment]
Do you have a user.css or some modified theme?

**Comment by IZA09** [comment]
on a1111? no. its set to default, on the browser itself its all default.

**Comment by DominikDoom** [comment]
Yeah, I just wanted to make sure there isn't some gradio theme or local style edit for the webui that hides the popup. user.css specifically would be a file in the webui root where you can add custom style rules.
For example, I limited the maximum width of the page in mine since I like to have the content centered on the monitor instead of up to the edges.

Since it seems to work there, it really must have to do either with a displaying issue or the tags themselves not loading for some reason.

Also in the browser developer tools, open the "Network" tab, enter "tag" in the Filter textbox at the top, and reload the page using CTRL+F5 with it open. It should show a list similar to this after the reload is finished:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/8c3de32a-4524-47ab-b8b1-f12c286f9385)
Check if any of these fail, which would show them in red.

**Comment by IZA09** [comment]
<img width="370" alt="Screenshot 2023-09-09 091436" src="https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/79812006/1ce913bd-acf1-4a8b-bf4a-acffe6c83c83">

all good here...

**Comment by DominikDoom** [comment]
wtf, now I really have no clue what else could be wrong.

Just for good measure, can you try typing in img2img and the new style editor prompts:
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/0d3c64eb-bcc9-48af-9819-5f11a36560e3)
To test if all text boxes are affected or only txt2img.

**Comment by IZA09** [comment]
yep its affected all throughout. this seems like a personal problem so ill just roll back to an older a1111. while id love to know whats going on here exactly, it looks to be a more obscure problem.

**Comment by DominikDoom** [comment]
Well, as the developer I of course want to find out too, so no worries.
I'd still recommend you try out a clean webui install some time instead of rolling back for a long period. *Something* with the update does seem to have broken it for you after all. The only change needed for autocomplete to work with the new version was addressed in issue #213, but that fix was added pre-release on the webui side and should definitely be there for you too.

**Comment by DominikDoom** [comment]
Something else I just noticed on your screenshots:
There are some oddities that seem style related, so maybe there actually is some issue with your webui installation.
![image](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/assets/34448969/53e9c28c-1941-4ce6-a439-d0bc3d975b09)

The textbox and sort order from the extra networks tabs should usually be hidden / removed if the generation tab is selected.
And the icon buttons below the image should normally be centered. The thick line below them is also usually not there.
Tried it out in Opera to make sure.

You could try downloading https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/style.css and replacing your local file in the webui root with it, in case the style file somehow got corrupted.

**Comment by IZA09** [comment]
im in the process of reinstalling the ui, if after that the problem persists, ill try out the css

**Comment by DominikDoom** [comment]
A fresh reinstall will also have the correct css, so it shouldn't be needed in that case.
Wishing you luck that it works 👍

**Comment by IZA09** [comment]
sweet jesus it works now after reinstalling 1.6.0.. i decided to run it through conda instead of the usual web-user.bat and somewhere along the line everything fell into place. though ill technically never know if it was conda or the fresh restart, everything's fully functional now. i want to apologies for the time and trouble and thank you very much for the assistance in this.

**Comment by DominikDoom** [comment]
No worries, glad you got it working and thanks for keeping me updated.
